### ISSUE TITLE
Form Flashes Red before React has Populated Fields

### ISSUE THREAD

**Issue by RyanPnayR** [RyanPnayR/issue-migration#26]
In gitlab by @nZac on Feb 7, 2018, 20:04

When a field is required and before the field has been populated the field flashes red.

**Comment by RyanPnayR** [comment]
In gitlab by @nZac on Feb 7, 2018, 20:05

marked this issue as related to #19

**Comment by RyanPnayR** [comment]
In gitlab by @nZac on Mar 3, 2018, 15:29

assigned to @randseay

**Comment by RyanPnayR** [comment]
In gitlab by @nZac on Mar 22, 2018, 23:26

I found out a little more about this. It is only in Firefox and this seems to fix it:

```css
:-moz-submit-invalid {
  box-shadow: none;
}

:-moz-ui-invalid {
  box-shadow:none;
}
```

However, it is worth reading this https://getbootstrap.com/docs/4.0/components/forms/#validation for the better way to do it.
